# This is the global configuration file for Gale.
# As you can see, there's a lot to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# 
# If you need help with the configuration or have any questions related to Gale,
# join us in our Discord, or check the GitHub Wiki pages.
# 
# The world configuration options are inside
# their respective world folder. The files are named gale-world.yml
# 
# Wiki: https://github.com/GaleMC/Gale/wiki
# Discord: https://discord.gg/gwezNT8c24

_version: 1
gameplay-mechanics:
  enable-book-writing: true
log-to-console:
  chat:
    empty-message-warning: false
    expired-message-warning: false
    not-secure-marker: true
    out-of-order-message-warning: false
  ignored-advancements: true
  invalid-pool-element-error-log-level: info
  invalid-statistics: true
  legacy-material-initialization: false
  null-id-disconnections: true
  player-login-locations: true
  plugin-library-loader:
    downloads: true
    library-loaded: true
    start-load-libraries-for-plugin: true
  set-block-in-far-chunk: true
  unrecognized-recipes: false
misc:
  ignore-null-legacy-structure-data: false
  include-in-timings-report:
    hardware-specs:
      cpu: true
      disks: true
      gpus: true
      memory: true
    server-properties:
      data-packs: true
      enable-rcon: false
      generator-settings: true
      level-name: false
      motd: false
      query-port: false
      rcon-port: false
      resource-pack-and-resource-pack-sha1: false
      resource-pack-prompt: false
      server-ip: false
      server-port: false
      text-filtering-config: false
  keepalive:
    send-multiple: true
  last-tick-time-in-tps-command:
    add-oversleep: false
    enabled: false
  premium-account-slow-login-timeout: -1
  verify-chat-order: true
small-optimizations:
  reduced-intervals:
    increase-time-statistics: 20
    update-entity-line-of-sight: 4
  use-xor-shift-random:
    auto-replenish-lootable-refill: true
    elytra-firework-speed: true
    entity-wake-up-duration: true
    generate-tree-with-bukkit-api: true
